#! /bin/sh

mount -t devtmpfs -o mode=0755 none /dev
mkdir -p /proc
mount -t proc proc /proc
mkdir -p /sys
mount -t sysfs sysfs /sys
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
hostname opencsl

insmod /samples/sample2.ko
