#! /bin/sh

#mount -t devtmpfs -o mode=0755 none /dev
mkdir -p /proc
mount -t proc proc /proc

mount -t tmpfs mdev /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

mkdir -p /sys
mount -t sysfs sysfs /sys

mount -a
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s


ifconfig eth0 192.168.1.111
hwclock -s

date
echo "BOOT DONE."

cd /samples
sh recording.sh &
